version: "3"

services:
  mysql:
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    networks:
      - overlay

  mongodb:
    image: mongo:latest
    hostname: mongodb
    environment:
      - MONGODB_DATABASE="test"
    networks:
      - overlay
    ports:
      - 27017:27017

  lib:
    build:
      context: .
    depends_on:
      - mysql
    networks:
      - overlay
    environment:
      WAIT_HOSTS: mysql:3306, mongodb:27017

networks:
  overlay:
